version: '3.4'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  donut:
    image: donut
    build:
      context: src/main/java
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - redis