spring:
  profiles:
    active: local

feign:
  client:
    config:
      default:
        logger-level: DEBUG

logging:
  level:
    com.example: DEBUG
    web: DEBUG
    org.springframework.web: DEBUG